services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    env_file:
      - ./postgresql/postgresql.env
    networks:
      - back-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  node-api:
    image: node-api
    container_name: node-api
    hostname: node-api
    env_file:
    - ./api-node/node-api.env
    - ./postgresql/postgresql.env
    networks:
      - back-network
      - front-network
    depends_on:
      - postgres

  angular-front:
    image: angular-front
    container_name: angular-front
    hostname: angular-front
    env_file:
      - ./api-node/node-api.env
    networks:
      - front-network
    ports:
      - 4200:80
    depends_on:
      - node-api

volumes:
  pg-data:
    external: true

networks:
  back-network:
    name: back-network
    driver: bridge
  front-network:
    name: front-network
    driver : bridge