FROM node:alpine

WORKDIR /code

COPY package.json /code/package.json
COPY package-lock.json /code/package-lock.json

RUN npm i install

COPY api/ /code
COPY env/ /code
COPY server.js /code

EXPOSE 3000

CMD [ "node","server.js" ]