FROM node:latest as build

WORKDIR /app

COPY package*.json /app

RUN npm install -g @angular/cli@latest @angular-devkit/build-angular
RUN npm install

COPY . /app

RUN npm run build --configuration=production

FROM nginx:stable-alpine3.17-slim

COPY --from=build /app/dist/front-angular/browser/ /usr/share/nginx/html/
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf