FROM node:current-alpine3.18 as build

EXPOSE 3000

WORKDIR /code

COPY . .

RUN npm i install --production

FROM node:hydrogen-alpine3.18
WORKDIR /server

COPY --from=build /code /server/

USER node

CMD [ "node","server.js" ]