FROM node:alpine as build

WORKDIR /code

COPY . .

RUN npm i install --production

FROM node:hydrogen-alpine3.18
WORKDIR /server

COPY --from=build /code /server/

CMD [ "node","server.js" ]